AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-018d291ca9ffc002f 
      InstanceType: t2.micro
      KeyName: us-west-1-harish
      SecurityGroups:
        - !Ref WebServerSecurityGroup
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "enable HTTP access via port 80 + SSH access"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
  KMSkey:
    Type: AWS::KMS::Key
    Properties: 
      Description: sample kms key
      Enabled: Boolean
      EnableKeyRotation: Boolean
      KeyPolicy: Json
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: true
      PendingWindowInDays: 30
      Tags: 
        - Tag
